#web:
  #driver_arguments:
    # The arguments to pass to the webdriver. E.g.: add --headless to run in headless mode
   # - --no-sandbox
   # - --disable-dev-shm-usage
  #urls:
    # base_url: The URL to start crawling with
    # prefix: Only crawl URLs matching the specified prefix
    # depth: The maximum depth for BFS traversal
    # You can add more websites by adding more entries (don't forget the - prefix from YAML)
    #- base_url: https://ai-on-openshift.io
    #  prefix: https://ai-on-openshift.io
    #  depth: 1
s3:
  # use_llama_parse: Use LlamaParse if `true`. Needs a `LLAMA_CLOUD_API_KEY` from https://cloud.llamaindex.ai set as environment variable
  use_llama_parse: false
